spring:
  application:
    name: member-manage-service
  datasource:
    url: jdbc:mysql://localhost:3306/auth
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    password: test
    username: test

server:
  port: 0 # random port for security reasons
  shutdown: graceful

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  level:
    org.springframework.jdbc: DEBUG
    org.springframework.transaction: DEBUG
    org.springframework.orm.jpa: DEBUG
